services:
  python:
    image: sozluk-python
    env_file:
      - ../../.local/django.env
      - ../../.local/postgres.env
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ../..:/app
